# Generated by Django 4.0 on 2023-10-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjecttest', '0002_schools_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='levels',
            field=models.CharField(choices=[('es', 'Easy'), ('md', 'Medium'), ('hd', 'Hard')], default='es', max_length=2),
        ),
    ]
