# Generated by Django 4.0 on 2023-10-14 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjecttest', '0003_questions_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='levels',
            field=models.CharField(choices=[('easy', 'Easy'), ('midl', 'Middle'), ('hard', 'Hard')], default='easy', max_length=4),
        ),
    ]
