# Generated by Django 4.0 on 2023-10-14 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjecttest', '0004_alter_questions_levels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjecttest.schools')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjecttest.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='clas',
            field=models.CharField(default='5-sinf', max_length=200),
        ),
        migrations.CreateModel(
            name='Pupils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=1)),
                ('birthday', models.DateField()),
                ('clas', models.ForeignKey(default='5-sinf', on_delete=django.db.models.deletion.CASCADE, to='subjecttest.class')),
                ('parents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjecttest.parents')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjecttest.schools')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjecttest.subjects')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjecttest.teachers')),
            ],
        ),
    ]
