# Generated by Django 4.0 on 2023-10-15 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjecttest', '0005_class_parents_theme_questions_clas_pupils'),
    ]

    operations = [
        migrations.AddField(
            model_name='parents',
            name='name',
            field=models.CharField(default="O'quvchining ota-onasi", max_length=200, verbose_name='Otasi yoki onasi ismi'),
        ),
        migrations.AddField(
            model_name='pupils',
            name='phone',
            field=models.CharField(default='999797367', max_length=14, verbose_name='Telefon raqami'),
        ),
        migrations.AddField(
            model_name='questions',
            name='theme',
            field=models.CharField(default='Qulay va tezkor hisoblash usullari', max_length=200),
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persentag', models.CharField(max_length=50)),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjecttest.pupils')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjecttest.subjects')),
            ],
        ),
    ]
